[package]
name = "noir"
type = "bin"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
# version error in rsa crate 0.3.1, keep both rsa and bignum are causing some issues.
rsa = { tag = "main", git = "https://github.com/noir-lang/noir_rsa" , directory = "lib" }
bignum = { tag = "v0.3.6", git = "https://github.com/noir-lang/noir-bignum" }